apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-tier
  labels: 
    app: microservices
    tier: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-tier
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70